# Generated by Django 5.1.7 on 2025-04-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_discountcode_order_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
    ]
