# Generated by Django 5.1.7 on 2025-04-21 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Mã giảm giá chỉ bao gồm chữ cái và số', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
