# Generated by Django 5.1.7 on 2025-04-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
    ]
